site_name: jascha.me
site_url: https://jascha.me/
theme:
  name: material
  palette:
    - scheme: default
      primary: ""
      accent: ""
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: ""
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
  logo: img/logo.png
  favicon: assets/images/favicon.png
  font:
    text: Sono
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaschadub
      name: jascha on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jascha
      name: jascha on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaschaw
      name: jascha on LinkedIn
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/jascha.me
      name: jascha on Bluesky
    - icon: fontawesome/brands/mastodon
      link: https://infosec.exchange/@jascha
      name: jascha on Mastodon
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/jaschadub
      name: jascha on Instagram

copyright: Copyright &copy; 2019 - 2025 Jascha Wanger

nav:
  - Home: index.md
  - About: about/index.md
  - Blog:
    - Overview: blog/index.md
    - Introducing AAEQ: blog/sample-post.md

plugins:
  - search
